services:
  api.controller.contacts.getContact:
    class: ContactList\Infrastructure\Controllers\GetContactController
    arguments:
      - '@api.query.contacts.getContactsHandler'
    public: true
  api.controller.contacts.contactCreate:
    class: ContactList\Infrastructure\Controllers\ContactCreateController
    arguments:
      - '@api.command.contacts.contactCreateHandler'
    public: true

